version: '2'

services:
  set_mappings:
    image: 'docker.elastic.co/logstash/logstash:6.6.0'
    network_mode: 'host'
    volumes:
      - '../dev-setup/:/dev-setup/'
    entrypoint: /bin/bash
    command: >
      -c "
        curl --user dev:changeme -XDELETE -H 'Content-Type: application/json' 'http://dev-search-v66.sixthdaycloudapps.net:9200/category_index?pretty' &&
        curl --user dev:changeme -XPUT -H 'Content-Type: application/json' 'http://dev-search-v66.sixthdaycloudapps.net:9200/category_index?pretty' --upload-file /dev-setup/elasticsearch/config/category_elasticsearch_mapping.json --retry 2;
      "

  logstash:
    image: 'docker.elastic.co/logstash/logstash:6.6.0'
    network_mode: 'host'
    volumes:
      - '../dev-setup/:/dev-setup/'
    entrypoint: /bin/bash
    environment:
      - ES_HOSTS=dev-search-v66.sixthdaycloudapps.net:9200
    command: >
      -c "
        logstash -f /dev-setup/elasticsearch/config/logstash-category-file-to-es.conf < /dev-setup/elasticsearch/data/category.txt;
        logstash -f /dev-setup/elasticsearch/config/logstash-leftnav-file-to-es.conf < /dev-setup/elasticsearch/data/leftnav.txt;
      "
    depends_on:
    - set_mappings