---
application_name: "navigation"
application_uri: "/navigation"
application_port: "8080"
product_team_name: "Storefront"
product_team_contact_email: "NMO_Storefront@neimanmarcus.com"
product_team_contact_cell: "111-111-1111"
product_team_contact_hipchat: "jkhashab"
resources:
  cpu: 1024
  memory: 2000
  min_containers: 1
  max_containers: 25
  desired_count: 1
  health_check:
    path: '/info'
docker:
  repository: "navigation-service"
  tag: "latest"
