version: '2'

services:
  set_mappings:
    image: 'logstash:5.6.12'
    network_mode: 'host'
    volumes:
      - '../bgdev-setup/:/bgdev-setup/'
    entrypoint: /bin/bash
    command: >
      -c "
        curl --user elastic:Neiman123 -XDELETE 'http://dev-east-search-bgv66.bgcloudapps.net:9200/category_index?pretty' &&
        curl --user elastic:Neiman123 -XPUT 'http://dev-east-search-bgv66.bgcloudapps.net:9200/category_index?pretty' -H 'Content-Type: application/json' --upload-file ./bgdev-setup/elasticsearch/config/category_elasticsearch_mapping.json --retry 2;
      "

  logstash:
    image: 'logstash:5.6.12'
    network_mode: 'host'
    volumes:
      - '../bgdev-setup/:/bgdev-setup/'
    entrypoint: /bin/bash
    environment:
      - ES_HOSTS=dev-east-search-bgv66.bgcloudapps.net:9200
    command: >
      -c "
        logstash -f ./bgdev-setup/elasticsearch/config/logstash-category-file-to-es.conf < ./bgdev-setup/elasticsearch/data/category.txt;
        logstash -f ./bgdev-setup/elasticsearch/config/logstash-leftnav-file-to-es.conf < ./bgdev-setup/elasticsearch/data/leftnav.txt;
      "
    depends_on:
    - set_mappings